name: assets_annotations
description: For Assets(localizations, images, icons)
version: 0.0.1
repository: https://github.com/abbos2101/assets_generator/tree/main/annotations
homepage: https://flutter.dev/
topics: [ assets, generators, localization, images, icons ]
funding: [ https://github.com/sponsors/abbos2101 ]

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0