name: res_generator
description: For Assets(localizations, images, icons)
version: 0.0.4
repository: https://github.com/abbos2101/assets_generator/tree/main/generators
homepage: https://flutter.dev/
topics: [ assets, generators, localization, images, icons ]
funding: [ https://github.com/sponsors/abbos2101 ]

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  build: any
  source_gen: any
  res_generator_annotation: ^0.0.4

dev_dependencies:
  lints: any