name: res_generator
description: For Assets(localizations, images, icons)
version: 0.0.7
repository: https://github.com/abbos2101/assets_generator/tree/main/generators
homepage: https://flutter.dev/
topics: [ assets, generators, localization, images, icons ]
funding: [ https://github.com/sponsors/abbos2101 ]

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  analyzer: ^6.5.0
  build: ^2.3.1
#  res_generator_annotation: ^0.0.5
  res_generator_annotation:
    path: ../annotations
  source_gen: ^1.4.0