name: res_generator
description: For Assets(localizations, images, icons)
version: 0.1.2
repository: https://github.com/abbos2101/assets_generator/tree/main/generators
homepage: https://flutter.dev/
topics: [ assets, generators, localization, images, icons ]
funding: [ https://github.com/sponsors/abbos2101 ]

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  yaml: ^3.1.2